name: 'my_dbt_project'
version: '1.0'
config-version: 2

profile: 'my_postgres_db'

profiles:
  my_postgres_db:   
    target: dev     
    outputs:
      dev:
        type: postgres
        host: 127.0.0.1
        port: 5432
        user: postgres
        pass: 12345678
        dbname: mydb
        schema: myschema


models:
  sample_data:
    customers:
      schema: my_source_schema
      table: customers
    sales:
      schema: my_source_schema
      table: sales

      